### ISSUE TITLE
Check MK RAW 2.1 - Error during mkp install of nutanix plugin

### ISSUE THREAD

**Issue by cotterse** [Yogibaer75/Check_MK-Things#24]
Hello,

I'm trying to install on my Check Mk RAW 2.1 your plugin for nutanix.
I have this :
OMD[etude]:~$ mkp list
OMD[etude]:~$ wget https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.0/nutanix/nutanix_prism-3.6-2.0.mkp
--2022-12-09 13:09:46--  https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.0/nutanix/nutanix_prism-3.6-2.0.mkp
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘nutanix_prism-3.6-2.0.mkp.1’

    [ <=>                                                                                                                                                                                                ] 143,052     --.-K/s   in 0.06s

2022-12-09 13:09:47 (2.14 MB/s) - ‘nutanix_prism-3.6-2.0.mkp.1’ saved [143052]

OMD[etude]:~$ mkp install nutanix_prism-3.6-2.0.mkp
Traceback (most recent call last):
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1682, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1659, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1522, in __init__
    self.firstmember = self.next()
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 2354, in next
    raise e
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 2327, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1112, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/omd/sites/etude/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/etude/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/etude/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/etude/lib/python3/cmk/base/modes/check_mk.py", line 742, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/etude/lib/python3/cmk/base/packaging.py", line 92, in do_packaging
    f(args)
  File "/omd/sites/etude/lib/python3/cmk/base/packaging.py", line 303, in package_install
    package = packaging.store_package(fh.read())
  File "/omd/sites/etude/lib/python3/cmk/utils/packaging.py", line 319, in store_package
    with tarfile.open(fileobj=BytesIO(file_content), mode="r:gz") as tar:
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1629, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1686, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

Could you help me ?

Thanks.

Kind regards.

**Comment by Yogibaer75** [comment]
Your wget command got no mkp file but something else. 143 kByte is way to big --> 10-12kByte would be ok

One other thing is you tried to installed the 2.0 package on 2.1 
wget https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.0/nutanix/nutanix_prism-3.6-2.0.mkp
this package is for 2.0

for 2.1 please try this
https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.1/nutanix/nutanix_prism-3.8-2.1.mkp
The version 3.7 that was there before had a small bug inside the special agent.

br
Andreas

**Comment by cotterse** [comment]
Not working with the good mkp file. same error :
[root@srv-supervision ~]# su etude
OMD[etude]:~$ wget https://github.com/Yogibaer75/Check_MK-Things/blob/master/che                                                                                                                                                             ck%20plugins%202.1/nutanix/nutanix_prism-3.8-2.1.mkp
--2022-12-09 14:00:11--  https://github.com/Yogibaer75/Check_MK-Things/blob/mast                                                                                                                                                             er/check%20plugins%202.1/nutanix/nutanix_prism-3.8-2.1.mkp
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘nutanix_prism-3.8-2.1.mkp’

    [ <=>                                   ] 143,052     --.-K/s   in 0.06s

2022-12-09 14:00:12 (2.35 MB/s) - ‘nutanix_prism-3.8-2.1.mkp’ saved [143052]

OMD[etude]:~$ mkp install nutanix_prism-3.8-2.1.mkp
Traceback (most recent call last):
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1682, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1659, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1522, in __init__
    self.firstmember = self.next()
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 2354, in next
    raise e
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 2327, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1112, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/omd/sites/etude/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/etude/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/etude/lib/python3/cmk/base/modes/__init__.py", line 69, in ca                                                                                                                                                             ll
    return handler(*handler_args)
  File "/omd/sites/etude/lib/python3/cmk/base/modes/check_mk.py", line 742, in m                                                                                                                                                             ode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/etude/lib/python3/cmk/base/packaging.py", line 92, in do_pack                                                                                                                                                             aging
    f(args)
  File "/omd/sites/etude/lib/python3/cmk/base/packaging.py", line 303, in packag                                                                                                                                                             e_install
    package = packaging.store_package(fh.read())
  File "/omd/sites/etude/lib/python3/cmk/utils/packaging.py", line 319, in store                                                                                                                                                             _package
    with tarfile.open(fileobj=BytesIO(file_content), mode="r:gz") as tar:
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1629, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1686, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
OMD[etude]:~$




Is it working with Check MK RAW ?

**Comment by Yogibaer75** [comment]
You download some webpage but not the mkp file.

```
Saving to: ‘nutanix_prism-3.8-2.1.mkp’

[ <=>                                   ] 143,052     --.-K/s   in 0.06s
2022-12-09 14:00:12 (2.35 MB/s) - ‘nutanix_prism-3.8-2.1.mkp’ saved [143052]
```
The download is 143kByte in size. Please check if some firewall/proxy is blocking your internet access from the monitoring server. 

The correct file size is 13065 Bytes

**Comment by cotterse** [comment]
12.8K on github for your file. I tried to download this file with another computer/Internet connection and the rsult is the same

**Comment by cotterse** [comment]
Find !
OMD[etude]:/tmp$ ls -al
total 160
drwxrwxrwt.  9 root root   4096 Dec  9 15:00 ./
dr-xr-xr-x. 17 root root    244 Mar 11  2021 ../
drwxrwxrwt.  2 root root      6 Jun 24  2020 .font-unix/
drwxrwxrwt.  2 root root      6 Jun 24  2020 .ICE-unix/
-rw-r--r--.  1 root root 143168 Dec  9 14:53 nutanix_prism-3.8-2.1.1.mkp
-rw-r--r--.  1 root root  13065 Dec  9 14:53 nutanix_prism-3.8-2.1.mkp


OMD[etude]:/tmp$ mkp install nutanix_prism-3.8-2.1.mkp
OMD[etude]:/tmp$ mkp list
nutanix_prism
