### ISSUE TITLE
Unable to install mkp package "not gzip file"

### ISSUE THREAD

**Issue by cotterse** [Yogibaer75/Check_MK-Things#28]
Hello

I'm trying to install nutanix_prism_21-4.0.0.mkp on my check mk RAW 2.1 and i have this message : 

OMD[etude]:~$ mkp install nutanix_prism_21-4.0.0.mkp
Traceback (most recent call last):
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1691, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1668, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1531, in __init__
    self.firstmember = self.next()
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 2363, in next
    raise e
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 2336, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1121, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/omd/sites/etude/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/omd/sites/etude/lib/python3.9/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/etude/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/etude/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/etude/lib/python3/cmk/base/modes/check_mk.py", line 742, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/etude/lib/python3/cmk/base/packaging.py", line 95, in do_packaging
    f(args)
  File "/omd/sites/etude/lib/python3/cmk/base/packaging.py", line 327, in package_install
    package = packaging.store_package(fh.read())
  File "/omd/sites/etude/lib/python3/cmk/utils/packaging.py", line 330, in store_package
    with tarfile.open(fileobj=BytesIO(file_content), mode="r:gz") as tar:
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1638, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/etude/lib/python3.9/tarfile.py", line 1695, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
OMD[etude]:~$

Could you help me ?

Thanks

KR.

**Comment by Yogibaer75** [comment]
It looks like a download problem for the mkp package. I used the package here from github as test and it is working without problem.

**Comment by albarki** [comment]
I have the same issue
```
OMD[xxx]:~$ mkp -P install nutanix_prism_21-4.0.0.mkp
Traceback (most recent call last):
  File "/omd/sites/isu/lib/python3.8/tarfile.py", line 1674, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/isu/lib/python3.8/tarfile.py", line 1651, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/isu/lib/python3.8/tarfile.py", line 1514, in __init__
    self.firstmember = self.next()
  File "/omd/sites/isu/lib/python3.8/tarfile.py", line 2318, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/isu/lib/python3.8/tarfile.py", line 1104, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/isu/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/omd/sites/isu/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/isu/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/omd/sites/isu/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/isu/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/isu/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/isu/lib/python3/cmk/base/modes/check_mk.py", line 654, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/isu/lib/python3/cmk/base/packaging.py", line 89, in do_packaging
    f(args)
  File "/omd/sites/isu/lib/python3/cmk/base/packaging.py", line 288, in package_install
    packaging.install_by_path(path)
  File "/omd/sites/isu/lib/python3/cmk/utils/packaging.py", line 352, in install_by_path
    return install(file_object=cast(BinaryIO, f))
  File "/omd/sites/isu/lib/python3/cmk/utils/packaging.py", line 356, in install
    package = _get_package_info_from_package(file_object)
  File "/omd/sites/isu/lib/python3/cmk/utils/packaging.py", line 490, in _get_package_info_from_package
    tar = tarfile.open(fileobj=file_object, mode="r:gz")
  File "/omd/sites/isu/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/isu/lib/python3.8/tarfile.py", line 1678, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
```

**Comment by Yogibaer75** [comment]
> I have the same issue

You are sure that the downloaded file is not corrupt?
I tested it as mentioned before and had no problem.

**Comment by albarki** [comment]
Hi @Yogibaer75 

Yes, I am sure I downloaded the file correctly and it is not corrupted. please try to download it yourself, then install it in a new environment if possible.

**Comment by Yogibaer75** [comment]
Tested and is working without problem
```
OMD[cmk]:~$ curl 'https://raw.githubusercontent.com/Yogibaer75/Check_MK-Things/master/check%20plugins%202.1/nutanix/nutanix_prism_21-4.0.0.mkp' -o nutanix_prism_21-4.0.0.mkp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16722  100 16722    0     0  49176      0 --:--:-- --:--:-- --:--:-- 49327
OMD[cmk]:~$ cmk -P install nutanix_prism_21-4.0.0.mkp 
OMD[cmk]:~$ cmk -vvP list 
Name             Version Title                                            Author                                                                    Req. Version Until Version Files State                        
---------------- ------- ------------------------------------------------ ------------------------------------------------------------------------- ------------ ------------- ----- -----------------------------
nutanix_prism_21 4.0.0   Nutanix Prism Special Agent and Checks - CMK 2.1 Andreas Doehler (andreas.doehler@bechtle.com / andreas.doehler@gmail.com) 2.1.0        2.2.0         60    Enabled (active on this site)
OMD[cmk]:~$
```
Pay attention this is a CMK 2.1 package.
