### ISSUE TITLE
error_installing_2.3.37

### ISSUE THREAD

**Issue by olni** [Yogibaer75/Check_MK-Things#55]
..tried to install the plugin and the following error occured:
`MK-Things/check plugins 2.3/redfish$ mkp add redfish-2.3.37.mkp 
Traceback (most recent call last):
  File "/omd/sites/monitoring/bin/mkp", line 35, in <module>
    sys.exit(cli.main(sys.argv[1:] or ["--help"], _PATH_CONFIG))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/monitoring/lib/python3/cmk/utils/packaging/cli.py", line 490, in main
    return args.handler(args, path_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/monitoring/lib/python3/cmk/utils/packaging/cli.py", line 254, in _command_add
    manifest = PackageStore().store(file_content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/monitoring/lib/python3/cmk/utils/packaging/__init__.py", line 134, in store
    package = extract_manifest(file_content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/monitoring/lib/python3/cmk/utils/packaging/_mkp.py", line 145, in extract_manifest
    return Manifest.parse_python_string(raw_info.decode())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/monitoring/lib/python3/cmk/utils/packaging/_mkp.py", line 84, in parse_python_string
    return cls.parse_obj(ast.literal_eval(raw))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/monitoring/lib/python3.11/site-packages/pydantic/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/omd/sites/monitoring/lib/python3.11/site-packages/pydantic/main.py", line 342, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Manifest
files -> __key__
  value is not a valid enumeration member; permitted: 'ec_rule_packs', 'agent_based', 'checks', 'inventory', 'checkman', 'agents', 'notifications', 'gui', 'web', 'pnp-templates', 'doc', 'locales', 'bin', 'lib', 'mibs', 'alert_handlers' (type=type_error.enum; enum_values=[<PackagePart.EC_RULE_PACKS: 'ec_rule_packs'>, <PackagePart.AGENT_BASED: 'agent_based'>, <PackagePart.CHECKS: 'checks'>, <PackagePart.HASI: 'inventory'>, <PackagePart.CHECKMAN: 'checkman'>, <PackagePart.AGENTS: 'agents'>, <PackagePart.NOTIFICATIONS: 'notifications'>, <PackagePart.GUI: 'gui'>, <PackagePart.WEB: 'web'>, <PackagePart.PNP_TEMPLATES: 'pnp-templates'>, <PackagePart.DOC: 'doc'>, <PackagePart.LOCALES: 'locales'>, <PackagePart.BIN: 'bin'>, <PackagePart.LIB: 'lib'>, <PackagePart.MIBS: 'mibs'>, <PackagePart.ALERT_HANDLERS: 'alert_handlers'>])
`
Is there something what i've missed? We are on checkmk 2.2.0p24
Regards,
Oliver

**Comment by olni** [comment]
1.

**Comment by olni** [comment]
..sorry, my fault. please delete

**Comment by Yogibaer75** [comment]
I think this is only the problem with the wrong package version for CMK 2.2.
The package you tried is for CMK 2.3

**Comment by olni** [comment]
...ah sorry i thought it's the 2.3.37 newest plugin version :-|
Using 2.2.33 works fine.
Thank you!
