### ISSUE TITLE
Dell PowerVault ME4 plugin throws exceptions with CheckMK 2.3.0

### ISSUE THREAD

**Issue by mbunkus** [Yogibaer75/Check_MK-Things#58]
CheckMK version: 2.3.0p2.cee
Plugin version: 3.3.0

Each time the special agent is executed it throws the following exception:

```
OMD[linet_bs]:~/local$ share/check_mk/agents/special/agent_dellpowervault -u monitoring -p <removed> exeter1.bs.linet-services.de
<<<dell_powervault_me4_controllers:sep(0)>>>
Traceback (most recent call last):
  File "/opt/omd/sites/linet_bs/local/share/check_mk/agents/special/agent_dellpowervault", line 84, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/omd/sites/linet_bs/local/share/check_mk/agents/special/agent_dellpowervault", line 78, in main
    w.append_json(response)
  File "/omd/sites/linet_bs/lib/python3/cmk/special_agents/v0_unstable/agent_common.py", line 62, in append_json
    self.writeline(json.dumps(data, sort_keys=True))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/linet_bs/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/omd/sites/linet_bs/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/linet_bs/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/omd/sites/linet_bs/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
```

Changing the last line in the following code…

``` python
    for element in commands:
        response = s.get(url + "/api/show/" + element, timeout=5)
        with SectionWriter(f"dell_powervault_me4_{element.replace('-', '_')}") as w:
            w.append_json(response)
```

to the following fixes the exception:

``` python
            w.append(response.json())
```

Unfortunately even with this fix no services are detected anymore for my ME4. Therefore more fixes might be required. Haven't had the time to dig deeper into why yet.

**Comment by Yogibaer75** [comment]
`w.append(response.json())` will not work it must be `w.append_json(response.json())`
fixed
https://github.com/Yogibaer75/Check_MK-Things/commit/c7a35353122e9dfbfca3e4a0f4a8a8e6758890b3
