### ISSUE TITLE
cant remove redfish version 2.3.38

### ISSUE THREAD

**Issue by unclesam87** [Yogibaer75/Check_MK-Things#65]
hey, 
i tried to update from the old hpe ilo plugin to redfish, as i installed the newest version from the git (2.3.50) i recongized that their is still an 2.3.38 on my checkmk that i couldnt remove over the webui - so i tried it over the console and got the following error:
Removing package redfish...
Traceback (most recent call last):
  File "/omd/sites/site/bin/mkp", line 76, in <module>
    cli.main(
  File "/omd/sites/site/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 798, in main
    args.handler(
  File "/omd/sites/site/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 84, in wrapped
    return wrappee(site_context, args, path_config, persisting_function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/site/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 441, in _command_remove
    package_store.remove(package_id)
  File "/omd/sites/site/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 116, in remove
    (self.local_packages / format_file_name(package_id)).unlink()
  File "/omd/sites/site/lib/python3.12/pathlib.py", line 1342, in unlink
    os.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/omd/sites/site/var/check_mk/packages_local/redfish-2.3.38.mkp'

manually copying that mkp file in that direcotry didnt do anything else then showing up as two 2.3.38 installed - one that i can remove, and one that produces the error above

**Comment by Yogibaer75** [comment]
The 2.3.38 is shipped within the CMK package. You only have to install the newer one.
The old package stays inside CMK, it cannot be removed.

**Comment by unclesam87** [comment]
thx for clearing that up!
is there an possibility to fix it that u see two versions then? that is quite confusing;)

**Comment by Yogibaer75** [comment]
What do you mean? It is no problem to install a newer version and have only this newer version active.
Looks like this.
<img width="392" alt="image" src="https://github.com/user-attachments/assets/d365633c-8c45-4532-9b95-2046acf20a27">
