### ISSUE TITLE
Checkmk: FortiGate Update MKP problem

### ISSUE THREAD

**Issue by JF-JX** [Yogibaer75/Check_MK-Things#71]
Hi Hi,
I am using this MKP: https://exchange.checkmk.com/p/fortigate-update
After activating it, the "Check_MK Discovery" Services crashes on the FortiGate hosts.
Doing a "cmk -I" says: "WARNING: Exception in discovery function of check plug-in 'fortigate_update': 'item' must be a non empty string or ommited entirely, got ''".
The checks however work fine.
This is the latest MKP Version, I am on Checkmk Enterprise 2.3p10, Ubuntu 22.04.4 LTS.

**Comment by Yogibaer75** [comment]
Yes this is the latest version i made.
It would be good if you execute the "cmk --debug -vvI" for this host and post only the crash message.
Or you can sent me the following SNMP table.
OID .1.3.6.1.4.1.12356.101.4.6.3.2.2.1
Inside this table all the relevant information for this check can be found.

**Comment by JF-JX** [comment]
Traceback (most recent call last):
  File "/omd/sites/main/bin/cmk", line 114, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/main/lib/python3/cmk/base/modes/__init__.py", line 70, in call
    return handler(*handler_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/main/lib/python3/cmk/base/modes/check_mk.py", line 1966, in mode_discover
    commandline_discovery(
  File "/omd/sites/main/lib/python3/cmk/checkengine/discovery/_commandline.py", line 76, in commandline_discovery
    _commandline_discovery_on_host(
  File "/omd/sites/main/lib/python3/cmk/checkengine/discovery/_commandline.py", line 154, in _commandline_discovery_on_host
    discovered_services = discover_services(
                          ^^^^^^^^^^^^^^^^^^
  File "/omd/sites/main/lib/python3/cmk/checkengine/discovery/_services.py", line 125, in discover_services
    {
  File "/omd/sites/main/lib/python3/cmk/checkengine/discovery/_services.py", line 186, in _discover_plugins_services
    yield from plugin.function(check_plugin_name, **kwargs)
  File "/omd/sites/main/lib/python3/cmk/base/checkers.py", line 884, in __discovery_function
    yield from (
  File "/omd/sites/main/lib/python3/cmk/base/checkers.py", line 884, in <genexpr>
    yield from (
               ^
  File "/omd/sites/main/lib/python3/cmk/base/api/agent_based/register/check_plugins.py", line 71, in filtered_generator
    for element in generator(*args, **kwargs):
  File "/omd/sites/main/local/lib/python3/cmk/base/plugins/agent_based/fortigate_update.py", line 51, in discover_fortigate_update
    yield Service(item=key)
          ^^^^^^^^^^^^^^^^^
  File "/omd/sites/main/lib/python3.12/site-packages/cmk/agent_based/v1/_checking_classes.py", line 117, in __new__
    item=cls._parse_item(item),
         ^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/main/lib/python3.12/site-packages/cmk/agent_based/v1/_checking_classes.py", line 128, in _parse_item
    raise TypeError(f"'item' must be a non empty string or ommited entirely, got {item!r}")
TypeError: 'item' must be a non empty string or ommited entirely, got ''

**Comment by Yogibaer75** [comment]
I made a small change in the discovery function.
This should fix your problem.
Fixed with 3acd26c

**Comment by JF-JX** [comment]
Thank you, works now :)
