### ISSUE TITLE
Checkmk Enterprise Edition 2.3.0p15 & dell-powervault-me4 3.3.2 

### ISSUE THREAD

**Issue by der-auserwaehlte** [Yogibaer75/Check_MK-Things#76]
no connection to the powervault

user / logindata for the connection provided is correct

[special_dellpowervault] requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /api/login/28f7f47050b31c118eb7bcc0497e78069abf27df684382a0b9c066defe37f865 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f348c7a4b00>, 'Connection to x.x.x.x timed out. (connect timeout=5)'))CRIT, [piggyback] Success (but no data found for this host), execution time 5.3 sec

**Comment by Yogibaer75** [comment]
First you should execute the special agent manually and with option "-v" and "--debug" for a possible better output.
The command line you get with "cmk -D hostname" as site user.

But as the exception happens at the very first request i think that your powervault is not reachable from the monitoring host.

**Comment by der-auserwaehlte** [comment]
Hi, the SAN is reachable from the monitoring host. also ping is fine. Firmware from the SAN is GT280R011-01. There was a bug in the R010-01 bevor affecting the SNMP functionality, there is also one newer Firmware version but there is nothing in the changelog.
https://www.dell.com/support/kbdoc/de-de/000203029/powervault-me4-der-snmp-dienst-reagiert-nicht-mehr-auf-abfragen-wenn-firmware-gt280r010-01-ausgef%C3%BChrt-wird

`OMD[customersite]:~$ cmk -v --debug SANDELL08
+ FETCHING DATA
Get data from program
No piggyback files for 'SANDELL08'. Skip processing.
No piggyback files for 'x.x.x.x'. Skip processing.
Get piggybacked data
+ EXECUTING INVENTORY PLUGINS
No piggyback files for 'SANDELL08'. Skip processing.
No piggyback files for 'x.x.x.x'. Skip processing.
[special_dellpowervault] requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /api/login                                                                                                      /28f7f47050b31c118eb7bcc0497e78069abf27df684382a0b9c066defe37f865 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2f1fd                                                                                                      26d80>, 'Connection to x.x.x.x timed out. (connect timeout=5)'))(!!), [piggyback] Success (but no data found for this host), execution time 5.3 sec execution_time=5.330 user_time=0.010 system_time=0.010 children_user_time=0.270 children_system_time=0.020 cmk_time_ds=5.020 cmk_time_agent=0.000
Agent exited with code 1: Traceback (most recent call last):
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f2f1fd26d80>, 'Connection to x.x.x.x timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/customersite/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /api/login/28f7f47050b31c118eb7bcc049                                                                                                      7e78069abf27df684382a0b9c066defe37f865 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2f1fd26d80>, 'Connection to x.x.x.x timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/customersite/local/share/check_mk/agents/special/agent_dellpowervault", line 99, in <module>
    sys.exit(main())
             ^^^^^^
  File "/omd/sites/customersite/local/share/check_mk/agents/special/agent_dellpowervault", line 86, in main
    r = fetch_url(s, url + "/api/login/" + auth_string, verify, timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/local/share/check_mk/agents/special/agent_dellpowervault", line 67, in fetch_url
    return session.get(url, verify=verify, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/customersite/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /api/login/28f7f47050b31c118eb7bcc0                                                                                                      497e78069abf27df684382a0b9c066defe37f865 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2f1fd26d80>, 'Connection to x.x.x.x timed out. (connect timeout=5)'))(!!)
`

**Comment by Yogibaer75** [comment]
I don't think that the device is reachable from the monitoring machine.
Simple test - curl -v https://x.x.x.x/api/login/28f7f47050b31c118eb7bcc0 497e78069abf27df684382a0b9c066defe37f865

**Comment by der-auserwaehlte** [comment]
Thank you for the assistance, got it working again
