### ISSUE TITLE
agent_netappeseries - errors

### ISSUE THREAD

**Issue by czKKill** [Yogibaer75/Check_MK-Things#8]
Hello,

Thank you for this plugin/check! I was searching for something like this for long time.

I'm trying to make it work with our E28xx (running latest 11.70.2) and I'm hitting some issues:
```
OMD[prod]:~$ ./local/share/check_mk/agents/special/agent_netappeseries -u user -s password IP
<<<netapp_eseries_batteries:sep(0)>>>
{'batteries_0900000000000000000001000000000000000000': {'batteryRef': '0900000000000000000001000000000000000000', 'status': 'optimal', 'physicalLocation': {'trayRef': '0E00000000000000000000000000000000000000', 'slot': 1, 'locationParent': {'refType': 'controller', 'controllerRef': '070000000000000000000001', 'symbolRef': None, 'typedReference': None}, 'locationPosition': 1, 'label': ''}, 'batteryAge': 1710, 'batteryLifeRemaining': -1, 'batteryTypeData': {'batteryType': 'dualIndividualFrus', 'cruParentController': None, 'parentController': '070000000000000000000001'}, 'reserved1': '0000000000000000', 'reserved2': '', 'manufacturerDate': '1475280000', 'vendorName': 'VN NETAPP  ', 'vendorPN': 'PN 271-00061+A0', 'vendorSN': 'SN SU64280362SO', 'fruType': 'FT IBATTERY', 'rtrAttributes': {'cruType': 'unknown', 'parentCru': None, 'rtrAttributeData': None}, 'repairPolicy': {'removalData': {'removalMethod': 'parent', 'rtrAttributes': None}, 'replacementMethod': 'self'}, 'batteryCanExpire': False, 'automaticAgeReset': True, 'learnCycleData': {'lastBatteryLearnCycle': '1640217600', 'nextBatteryLearnCycle': '1645056000', 'batteryLearnCycleInterval': 8}, 'smartBatteryData': {'lastBatteryLearnCycle': '1640217600', 'nextBatteryLearnCycle': '1645056000', 'batteryLearnCycleInterval': 8}, 'id': '0900000000000000000001000000000000000000'}, 'batteries_0900000000000000000002000000000000000000': {'batteryRef': '0900000000000000000002000000000000000000',
'status': 'optimal', 'physicalLocation': {'trayRef': '0E00000000000000000000000000000000000000', 'slot': 2, 'locationParent': {'refType': 'controller', 'controllerRef': '070000000000000000000002', 'symbolRef': None, 'typedReference': None}, 'locationPosition': 1, 'label': ''}, 'batteryAge': 1710, 'batteryLifeRemaining': -1, 'batteryTypeData': {'batteryType': 'dualIndividualFrus', 'cruParentController': None, 'parentController': '070000000000000000000002'}, 'reserved1': '0000000000000000', 'reserved2': '', 'manufacturerDate': '1475280000', 'vendorName': 'VN NETAPP  ', 'vendorPN': 'PN 271-00061+A0', 'vendorSN': 'SN SU64280399SO', 'fruType': 'FT IBATTERY', 'rtrAttributes': {'cruType': 'unknown', 'parentCru': None, 'rtrAttributeData': None}, 'repairPolicy': {'removalData': {'removalMethod': 'parent', 'rtrAttributes': None},
'replacementMethod': 'self'}, 'batteryCanExpire': False, 'automaticAgeReset': True, 'learnCycleData': {'lastBatteryLearnCycle': '1640217600', 'nextBatteryLearnCycle': '1645056000', 'batteryLearnCycleInterval': 8}, 'smartBatteryData': {'lastBatteryLearnCycle': '1640217600', 'nextBatteryLearnCycle': '1645056000', 'batteryLearnCycleInterval': 8}, 'id': '0900000000000000000002000000000000000000'}}
<<<netapp_eseries_controllers:sep(0)>>>
Traceback (most recent call last):
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 460, in <module>
    main()
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 456, in main
    fetch_storage_data(session, sections, args, base_url, controller_ids)
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 163, in fetch_storage_data
    combined_storage_data = add_perfdata_to_section_data(
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 213, in add_perfdata_to_section_data
    if item[identifier] == perfitem[section.perfdata_identifier]:
KeyError: None
```

The error above is showing for controllers, drives, system and volumes sections.
Unfortunately, my Python skills are basically non-existent, so I've butchered it by setting `perfdata_uri=None` for these sections.
Then after doing that I had issue with two other sections:

1. system:
```
<<<netapp_eseries_system:sep(0)>>>
Traceback (most recent call last):
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 461, in <module>
    main()
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 457, in main
    fetch_storage_data(session, sections, args, base_url, controller_ids)
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 178, in fetch_storage_data
    handle_output(combined_storage_data, section.ident, section.name)
  File "./local/share/check_mk/agents/special/agent_netappeseries2", line 301, in handle_output
    output_dict.setdefault(object_typ + '_' + element[options].strip(),
TypeError: string indices must be integers
```
2. drives - no error on the check side, but in cmk I had a plugin crash for each drive:
Exception: `TypeError (__new__() takes 3 positional arguments but 7 were given)`
Traceback:
```
  File "/omd/sites/prod/lib/python3/cmk/base/checking.py", line 581, in get_aggregated_result
    result = _aggregate_results(check_function(**kwargs))
  File "/omd/sites/prod/lib/python3/cmk/base/checking.py", line 812, in _aggregate_results
    perfdata, results = _consume_and_dispatch_result_types(subresults)
  File "/omd/sites/prod/lib/python3/cmk/base/checking.py", line 856, in _consume_and_dispatch_result_types
    for subr in subresults:
  File "/omd/sites/prod/lib/python3/cmk/base/api/agent_based/register/check_plugins.py", line 89, in filtered_generator
    for element in generator(*args, **kwargs):
  File "/omd/sites/prod/local/lib/python3/cmk/base/plugins/agent_based/netapp_eseries_drives.py", line 61, in check_netapp_eseries_drives
    yield Metric("erase", erase_count, '', '', 0, 100)
```

Any idea what is causing these issues?

**Comment by Yogibaer75** [comment]
Can you please check with this https://github.com/chexma/checkmk_plugins/tree/master/netapp_eseries
version of the Netapp eSeries extension?
This is the actual version i had done together with my colleague.

If there are the same errors we need to investigate what is different on your eSeries models.

**Comment by czKKill** [comment]
I've installed the mkp from your link, and now I have a problem with the script itself - no matter with what arguments I'm trying to run it, I get:
```
OMD[prod]:~$ ./local/share/check_mk/agents/special/agent_netappeseries
Traceback (most recent call last):
  File "./local/share/check_mk/agents/special/agent_netappeseries", line 504, in <module>
    main()
  File "./local/share/check_mk/agents/special/agent_netappeseries", line 375, in main
    Section(
TypeError: __new__() missing 1 required positional argument: 'ident'
```

Using cmk 2.0.0p18.cre

**Comment by czKKill** [comment]
I was looking into it again, and I've found that it seems the discovery is working:

```
OMD[prod]:~$ cmk -D 10.2.12.61

10.2.12.61                                                                     
Addresses:              10.2.12.61
Tags:                   [address_family:ip-v4-only], [agent:special-agents], [criticality:test], [if_alias_desc:if_desc], [ip-v4:ip-v4], [networking:lan], [os:other], [owner:it], [piggyback:auto-piggyback], [site:prod], [snmp:snmp], [snmp_ds:snmp-v2], [tcp:tcp]
Labels:                 [https:8443]
Parents:                ttc-v08-3650
Host groups:            check_mk
Contact groups:         check-mk-notify, all
Agent mode:             No Checkmk agent, all configured special agents
Type of agent:
  SNMP (Community: 'snmpcomm', Bulk walk: yes, Port: 161, Backend: Classic)
  Program: /omd/sites/prod/local/share/check_mk/agents/special/agent_netappeseries -u 'monitor' -s 'passwd' '10.2.12.61'
  Process piggyback data from /omd/sites/prod/tmp/check_mk/piggyback/10.2.12.61
Services:
  checktype                  item                                                params
                                                                                                                                         description                                                   groups
  -------------------------- --------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------- ------
  netapp_eseries_batteries   batteries_0900000000000000000001000000000000000000  {'battery_state': 0}
                                                                                                                                         Battery batteries_0900000000000000000001000000000000000000
  netapp_eseries_batteries   batteries_0900000000000000000002000000000000000000  {'battery_state': 0}
                                                                                                                                         Battery batteries_0900000000000000000002000000000000000000
  netapp_eseries_controllers controllers_021703012190                            {'controller_state': 0}
                                                                                                                                         Controller controllers_021703012190
  netapp_eseries_controllers controllers_021703012238                            {'controller_state': 0}
                                                                                                                                         Controller controllers_021703012238
  netapp_eseries_fans        fans_0800000000000000000001000000000000000000       {'fan_state': 0}
                                                                                                                                         FAN fans_0800000000000000000001000000000000000000
  netapp_eseries_fans        fans_0800000000000000000002000000000000000000       {'fan_state': 0}
                                                                                                                                         FAN fans_0800000000000000000002000000000000000000
  netapp_eseries_fans        fans_0800000000000000000003000000000000000000       {'fan_state': 0}
                                                                                                                                         FAN fans_0800000000000000000003000000000000000000
  netapp_eseries_fans        fans_0800000000000000000004000000000000000000       {'fan_state': 0}
                                                                                                                                         FAN fans_0800000000000000000004000000000000000000
  netapp_eseries_interfaces  interfaces_2201000000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2201000000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2201010000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2201010000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2201020000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2201020000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2201030000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2201030000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2201040000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2201040000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2201050000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2201050000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2202000000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2202000000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2202010000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2202010000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2202020000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2202020000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2202030000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2202030000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2202040000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2202040000000000000000000000000000000000
  netapp_eseries_interfaces  interfaces_2202050000000000000000000000000000000000 {'interface_state': 0}
                                                                                                                                         Interface interfaces_2202050000000000000000000000000000000000
  netapp_eseries_pools       pools_04000000600A098000B2E42F0000011A5A1BD9B8      {'levels': (80.0, 90.0), 'magic_normsize': 20, 'levels_low': (70.0, 80.0), 'trend_range': 24, 'trend_perfdata': True, 'show_levels': 'onmagic', 'inodes_levels': (10.0, 5.0), 'show_inodes': 'onlow', 'show_reserved': False, 'magic': 0.6, 'trend_showtimeleft': True} Pool pools_04000000600A098000B2E42F0000011A5A1BD9B8
  snmp_info                  None                                                {}
                                                                                                                                         SNMP Info
  netapp_eseries_trays       trays_0E00000000000000000000000000000000000000      {'tray_state': 0}
                                                                                                                                         Tray trays_0E00000000000000000000000000000000000000
  uptime                     None                                                {}
                                                                                                                                         Uptime
  netapp_eseries_volumes     volumes_02000000600A098000B2E97D00000AF560378CFB    {'volume_state': 0}
                                                                                                                                         Volume volumes_02000000600A098000B2E97D00000AF560378CFB
```

But if I use the very same command directly I get the error mentioned above:
```
OMD[prod]:~$ /omd/sites/prod/local/share/check_mk/agents/special/agent_netappeseries -u 'monitor' -s 'passwd' '10.2.12.61'
Traceback (most recent call last):
  File "/omd/sites/prod/local/share/check_mk/agents/special/agent_netappeseries", line 504, in <module>
    main()
  File "/omd/sites/prod/local/share/check_mk/agents/special/agent_netappeseries", line 375, in main
    Section(
TypeError: __new__() missing 1 required positional argument: 'ident'
```

In CMK web iface I am able to discover services, but they're not monitored (all in PEND state + Check_MK service shows the error above)

**Comment by Yogibaer75** [comment]
I see what the problem is. 

    Section = namedtuple(
        "Section",
        ["name", "uri", "perfdata_uri", "perfdata_identifier", "ident"])
    sections = [

Remove the "ident" from the list. Then it should work.

**Comment by czKKill** [comment]
Confirmed it works now, thank you!

**Comment by Yogibaer75** [comment]
I will make a pull request then the next version should work out of the box.
