### ISSUE TITLE
Redfish on Checkmk 2.2 - Error

### ISSUE THREAD

**Issue by pietro95** [Yogibaer75/Check_MK-Things#83]
Hello, I'm in a Distribuited Monitoring Enviroment and we are slowly upgrading from Checkmk 2.1 to Checkmk 2.2. 

Main Site is still at 2.1p49 (while we update all the slaves), while the firsts updated slaves are on 2.2p37. Redfish plugin is updated to 2.2.60.

We have a bunch of Lenovo XCC monitored and on the first two updated site we encountered the following error:

```
Agent exited with code 1: Agent failed - please submit a crash report! (Crash-ID: 2859357a-bc94-11ef-b05e-dfbcc231cf72)

Traceback (most recent call last):
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/connectionpool.py", line 466, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/connectionpool.py", line 461, in _make_request
httplib_response = conn.getresponse()
^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/lib/python3.11/http/client.py", line 1395, in getresponse
response.begin()
File "/omd/sites/MYSITENAME/lib/python3.11/http/client.py", line 325, in begin
version, status, reason = self._read_status()
^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/lib/python3.11/http/client.py", line 286, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/lib/python3.11/socket.py", line 718, in readinto
return self._sock.recv_into(b)
^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/lib/python3.11/ssl.py", line 1314, in recv_into
return self.read(nbytes, buffer)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/lib/python3.11/ssl.py", line 1166, in read
return self._sslobj.read(len, buffer)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/MYSITENAME/local/lib/python3/requests/adapters.py", line 486, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/connectionpool.py", line 798, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/packages/six.py", line 770, in reraise
raise value
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/connectionpool.py", line 714, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/connectionpool.py", line 468, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/omd/sites/MYSITENAME/local/lib/python3/urllib3/connectionpool.py", line 357, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.0.100.1', port=443): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/MYSITENAME/local/lib/python3/redfish/rest/v1.py", line 910, in _rest_request
resp = self._session.request(method.upper(), "{}{}".format(self.__base_url, reqpath), data=body,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/requests/adapters.py", line 532, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10.0.100.1', port=443): Read timed out. (read timeout=3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/omd/sites/MYSITENAME/lib/python3/cmk/special_agents/utils/agent_common.py", line 149, in _special_agent_main_core
return main_fn(args)
^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/share/check_mk/agents/special/agent_redfish", line 725, in agent_redfish_main
get_information(redfishobj, sections)
File "/omd/sites/MYSITENAME/local/share/check_mk/agents/special/agent_redfish", line 563, in get_information
firmwares = fetch_data(
^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/share/check_mk/agents/special/agent_redfish", line 130, in fetch_data
response_url = redfishobj.get(url, None)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/redfish/rest/v1.py", line 628, in get
return self._rest_request(path, method='GET', args=args,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/redfish/rest/v1.py", line 1110, in _rest_request
return super(HttpClient, self)._rest_request(path=path, method=method,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/MYSITENAME/local/lib/python3/redfish/rest/v1.py", line 954, in _rest_request
raise RetriesExhaustedError() from cause_exception
redfish.rest.v1.RetriesExhaustedError
```

Do you have any suggestion?

**Comment by pietro95** [comment]
So I think that I managed to solve the problem setting the timeout to 20 but I think is more a workaround that a real solution...

**Comment by Yogibaer75** [comment]
File "/omd/sites/MYSITENAME/local/share/check_mk/agents/special/agent_redfish", line 563, in get_information
firmwares = fetch_data(
^^^^^^^^^^^

I think you have to disable the firmware section for these devices.
It takes to long in your case.

**Comment by Yogibaer75** [comment]
As extra comment for your problem - this whole timeout problem with firmware fetching is obsolete with 2.3 version then as you can define cache time for single sections and the firmware section uses an way higher timeout.
